
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Bus_Stop extends javax.swing.JFrame {

    dbhelper db = new dbhelper();
    /**
     * Creates new form Bus_Stop
     */
    public Bus_Stop() {
        initComponents();
        AutoIncrement();
        db.getTable(jTable1, "select * from bus_stop");
        db.FillCombo(cmbroute_no, "select distinct(route_no) from route_info", "route_no");
        
    }

    public void ValidateBus_Stop() {
        if (txtBStop_Id.getText().equals("") || txtStop_no.getText().equals("") || txtStop_name.getText().equals("") || txtFare_stage.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
            return;
        }
    }
    
    public void clearText() {
        txtBStop_Id.setText("");
        txtStop_no.setText("");
        txtStop_name.setText("");
        txtFare_stage.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblFare_stage = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblRoute_no = new javax.swing.JLabel();
        lblStop_no = new javax.swing.JLabel();
        lblStop_name = new javax.swing.JLabel();
        txtFare_stage = new javax.swing.JTextField();
        txtBStop_Id = new javax.swing.JTextField();
        txtStop_no = new javax.swing.JTextField();
        txtStop_name = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        cmbroute_no = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        jLabel1.setText("Bus Stop");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 80));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFare_stage.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        lblFare_stage.setText("Fare Stage");
        jPanel3.add(lblFare_stage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblId.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        lblId.setText("ID");
        jPanel3.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblRoute_no.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        lblRoute_no.setText("Route No");
        jPanel3.add(lblRoute_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblStop_no.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        lblStop_no.setText("Stop No");
        jPanel3.add(lblStop_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblStop_name.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        lblStop_name.setText("Stop Name");
        jPanel3.add(lblStop_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel3.add(txtFare_stage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, 30));
        jPanel3.add(txtBStop_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 190, 30));
        jPanel3.add(txtStop_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, 30));
        jPanel3.add(txtStop_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jPanel3.add(cmbroute_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 390, 270));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Route_no", "Stop_no", "Stop_name", "are_stage"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 250));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 400, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ValidateBus_Stop();
        AutoIncrement();
        
        db.InsertData("insert into bus_stop(id,route_no,stop_no,stop_name,fare_stage) values ('" + txtBStop_Id.getText() + "','" + cmbroute_no.getSelectedItem().toString()+ "','" + txtStop_no.getText() + "','" + txtStop_name.getText() + "','" + txtFare_stage.getText() + "')");
        db.getTable(jTable1, "select * from bus_stop");
        
        clearText();
        AutoIncrement();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        db.updateRecord("update bus_stop set stop_name='" + txtStop_name.getText() + "',fare_stage='" + txtFare_stage.getText() + "' where id='" + txtBStop_Id.getText() + "'");
        db.getTable(jTable1, "select * from bus_stop");
        clearText();
        AutoIncrement();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        db.DeleteData("DELETE FROM `bus_stop` WHERE id='" + txtBStop_Id.getText() + "'");
        db.getTable(jTable1, "select * from bus_stop");
        clearText();
        AutoIncrement();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    
    public void AutoIncrement() {
        try {
            String s = "select MAX(id) from bus_stop";
            db.DataFound(s);
            int i = 0;
            while (db.rs.next()) {
                i = db.rs.getInt(1);
            }
            txtBStop_Id.setText(String.valueOf(i + 1));
        } catch (Exception e) {
            System.out.println(e);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bus_Stop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bus_Stop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bus_Stop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bus_Stop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bus_Stop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbroute_no;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFare_stage;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblRoute_no;
    private javax.swing.JLabel lblStop_name;
    private javax.swing.JLabel lblStop_no;
    private javax.swing.JTextField txtBStop_Id;
    private javax.swing.JTextField txtFare_stage;
    private javax.swing.JTextField txtStop_name;
    private javax.swing.JTextField txtStop_no;
    // End of variables declaration//GEN-END:variables
}
