
import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Report_Option extends javax.swing.JFrame {

    
    dbhelper db=new dbhelper();
     String m_where;
    String m_report_source = "/Bus_Management/";
    String m_sql_stmt;
    Map parametersMap = new HashMap();
    /**
     * Creates new form Report_Option
     */
    public Report_Option() {
        initComponents();
    }

    public void Show()
    {
         try {
            DBUtilities dbUtilities = new DBUtilities();
            InputStream is = getClass().getResourceAsStream(m_report_source);

            JRDesignQuery jrDesignQuery = new JRDesignQuery();
            jrDesignQuery.setText(m_sql_stmt);

            JasperDesign jasperDesign = JRXmlLoader.load(is);
            jasperDesign.setQuery(jrDesignQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametersMap, dbUtilities.getConnection());
            JasperViewer.viewReport(jasperPrint, false);

        } catch (SQLException | JRException e) {
            System.out.println("Exception message " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblRoute = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblBus_details = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblBus_Stop = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTour_Info = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblEmployee = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblScheudle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRoute.setFont(new java.awt.Font("Times New Roman", 3, 32)); // NOI18N
        lblRoute.setForeground(new java.awt.Color(51, 0, 51));
        lblRoute.setText("Route Report");
        lblRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRouteMouseClicked(evt);
            }
        });
        jPanel2.add(lblRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 310, 90));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBus_details.setFont(new java.awt.Font("Times New Roman", 3, 32)); // NOI18N
        lblBus_details.setForeground(new java.awt.Color(51, 0, 51));
        lblBus_details.setText("Bus Details Report");
        lblBus_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBus_detailsMouseClicked(evt);
            }
        });
        jPanel3.add(lblBus_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 310, 90));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBus_Stop.setFont(new java.awt.Font("Times New Roman", 3, 32)); // NOI18N
        lblBus_Stop.setForeground(new java.awt.Color(51, 0, 51));
        lblBus_Stop.setText("Bus Stop Report");
        lblBus_Stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBus_StopMouseClicked(evt);
            }
        });
        jPanel4.add(lblBus_Stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 90));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTour_Info.setFont(new java.awt.Font("Times New Roman", 3, 32)); // NOI18N
        lblTour_Info.setForeground(new java.awt.Color(51, 0, 51));
        lblTour_Info.setText("Trip Info Report");
        lblTour_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTour_InfoMouseClicked(evt);
            }
        });
        jPanel5.add(lblTour_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 310, 90));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmployee.setFont(new java.awt.Font("Times New Roman", 3, 32)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(51, 0, 51));
        lblEmployee.setText("Employee Report");
        lblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseClicked(evt);
            }
        });
        jPanel6.add(lblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 310, 90));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScheudle.setFont(new java.awt.Font("Times New Roman", 3, 32)); // NOI18N
        lblScheudle.setForeground(new java.awt.Color(51, 0, 51));
        lblScheudle.setText("Scheudle Report");
        lblScheudle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScheudleMouseClicked(evt);
            }
        });
        jPanel7.add(lblScheudle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 310, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRouteMouseClicked
        // TODO add your handling code here:
        m_report_source = "rptRoute.jrxml";
        m_sql_stmt = "SELECT route_info.`id` AS route_info_id, route_info.`route_no` AS route_info_route_no, route_info.`no_of_stop` AS route_info_no_of_stop, route_info.`start` AS route_info_start, route_info.`stop` AS route_info_stop, route_info.`start_time` AS route_info_start_time,route_info.`stop_time` AS route_info_stop_time FROM `route_info` route_info";
   Show();
    }//GEN-LAST:event_lblRouteMouseClicked

    private void lblBus_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBus_detailsMouseClicked
        // TODO add your handling code here:
        m_report_source = "rptBus_Details.jrxml";
        m_sql_stmt = "SELECT bus_details.`id` AS bus_details_id, bus_details.`bus_no` AS bus_details_bus_no, bus_details.`bus_type` AS bus_details_bus_type, bus_details.`min_charge` AS bus_details_min_charge, bus_details.`seat_no` AS bus_details_seat_no, bus_details.`depot` AS bus_details_depot, bus_details.`child_fare` AS bus_details_child_fare, bus_details.`adult_fare` AS bus_details_adult_fare FROM `bus_details` bus_details";
   Show();
    }//GEN-LAST:event_lblBus_detailsMouseClicked

    private void lblBus_StopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBus_StopMouseClicked
        // TODO add your handling code here:
        m_report_source = "rptBus_Stop.jrxml";
        m_sql_stmt = "SELECT bus_stop.`id` AS bus_stop_id, bus_stop.`route_no` AS bus_stop_route_no, bus_stop.`stop_no` AS bus_stop_stop_no, bus_stop.`stop_name` AS bus_stop_stop_name, bus_stop.`fare_stage` AS bus_stop_fare_stage FROM `bus_stop` bus_stop";
   Show();
    }//GEN-LAST:event_lblBus_StopMouseClicked

    private void lblTour_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTour_InfoMouseClicked
        // TODO add your handling code here:
        m_report_source = "rptTrip_Info.jrxml";
        m_sql_stmt = "SELECT trip_info.`id` AS trip_info_id, trip_info.`route_no` AS trip_info_route_no, trip_info.`bus_no` AS trip_info_bus_no, trip_info.`start_time` AS trip_info_start_time, trip_info.`stop_time` AS trip_info_stop_time, trip_info.`amount` AS trip_info_amount FROM `trip_info` trip_info";
   Show();
    }//GEN-LAST:event_lblTour_InfoMouseClicked

    private void lblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseClicked
        // TODO add your handling code here:
        m_report_source = "rptEmployee.jrxml";
        m_sql_stmt = "SELECT employee.`id` AS employee_id, employee.`name` AS employee_name, employee.`dob` AS employee_dob, employee.`address` AS employee_address, employee.`designatio` AS employee_designatio, employee.`mob` AS employee_mob, employee.`gender` AS employee_gender FROM `employee` employee";
   Show();
    }//GEN-LAST:event_lblEmployeeMouseClicked

    private void lblScheudleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheudleMouseClicked
        // TODO add your handling code here:
        m_report_source = "rptScheudle.jrxml";
        m_sql_stmt = "SELECT schedual.`id` AS schedual_id, schedual.`emp_name` AS schedual_emp_name, schedual.`bus_no` AS schedual_bus_no, schedual.`date` AS schedual_date, schedual.`route_no` AS schedual_route_no, schedual.`amount` AS schedual_amount FROM `schedual` schedual";
   Show();
    }//GEN-LAST:event_lblScheudleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblBus_Stop;
    private javax.swing.JLabel lblBus_details;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblRoute;
    private javax.swing.JLabel lblScheudle;
    private javax.swing.JLabel lblTour_Info;
    // End of variables declaration//GEN-END:variables
}
