
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Scheudle extends javax.swing.JFrame {

    dbhelper db = new dbhelper();
    
    /**
     * Creates new form Scheudle
     */
    public Scheudle() {
        initComponents();
        AutoIncrement();
         db.getTable(jTable1, "select * from schedual");
        db.FillCombo(cmbSch_RouteNO, "select distinct(route_no) from route_info", "route_no");
        db.FillCombo(cmbSch_BusNO, "select distinct(bus_no) from bus_details", "bus_no");
    }

    
    public void ValidateScheudle() {
        if (txtSch_ID.getText().equals("") ||  txtSch_TripAMT.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
            return;
        }
    }
    
    public void clearText() {
        txtSch_ID.setText("");
        txtSch_EmpName.setText("");
        txtSch_TripAMT.setText("");
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSch_TripAMT = new javax.swing.JTextField();
        txtSch_ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbSch_RouteNO = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dt = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cmbSch_BusNO = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtSch_EmpName = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Scheudle");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 80));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel2.setText("Trip Amt");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel3.setText("ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtSch_TripAMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSch_TripAMTActionPerformed(evt);
            }
        });
        jPanel3.add(txtSch_TripAMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 120, 30));

        txtSch_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSch_IDActionPerformed(evt);
            }
        });
        jPanel3.add(txtSch_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel5.setText("Emp Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jPanel3.add(cmbSch_RouteNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel6.setText("Bus NO");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));
        jPanel3.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel7.setText("Date");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel3.add(cmbSch_BusNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 160, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel8.setText("Route NO");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        txtSch_EmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSch_EmpNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtSch_EmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 150, 30));

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 90, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 90, 30));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 90, 30));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 90, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 820, 190));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Emp_ID", "Emp_Name", "Bus_No", "Date", "Route_NO", "Trip_Amt"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 240));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 820, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSch_TripAMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSch_TripAMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSch_TripAMTActionPerformed

    private void txtSch_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSch_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSch_IDActionPerformed

    private void txtSch_EmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSch_EmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSch_EmpNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ValidateScheudle();
        AutoIncrement();
        
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        
        String  date= sdf.format(dt.getDate()) ;

        System.out.println(date);
        
        db.InsertData("insert into schedual(id,emp_name,bus_no,date,route_no,amount) values ('" + txtSch_ID.getText() + "','" + txtSch_EmpName.getText()+ "','"+cmbSch_BusNO.getSelectedItem().toString()+"','" + date + "','" + cmbSch_RouteNO.getSelectedItem().toString()+ "','" + txtSch_TripAMT.getText() + "')");
        db.getTable(jTable1, "select * from schedual");
        
        clearText();
        AutoIncrement();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        db.updateRecord("update schedual set emp_name='" + txtSch_EmpName.getText() + "',amount='" + txtSch_TripAMT.getText() + "' where id='" + txtSch_ID.getText() + "'");
        db.getTable(jTable1, "select * from schedual");
        clearText();
        AutoIncrement();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        db.DeleteData("DELETE FROM `schedual` WHERE id='" + txtSch_ID.getText() + "'");
        db.getTable(jTable1, "select * from schedual");
        clearText();
        AutoIncrement();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    
    public void AutoIncrement() {
        try {
            String s = "select MAX(id) from schedual";
            db.DataFound(s);
            int i = 0;
            while (db.rs.next()) {
                i = db.rs.getInt(1);
            }
            txtSch_ID.setText(String.valueOf(i + 1));
        } catch (Exception e) {
            System.out.println(e);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scheudle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scheudle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scheudle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scheudle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scheudle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSch_BusNO;
    private javax.swing.JComboBox<String> cmbSch_RouteNO;
    private com.toedter.calendar.JDateChooser dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSch_EmpName;
    private javax.swing.JTextField txtSch_ID;
    private javax.swing.JTextField txtSch_TripAMT;
    // End of variables declaration//GEN-END:variables
}
