
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Trip_Information extends javax.swing.JFrame {

    
    dbhelper db = new dbhelper();
    /**
     * Creates new form Trip_Information
     */
    public Trip_Information() {
        initComponents();
        AutoIncrement();
        db.getTable(jTable1, "select * from trip_info");
        db.FillCombo(cmbTRoute_no, "select distinct(route_no) from route_info", "route_no");
        db.FillCombo(cmbTBus_no, "select distinct(bus_no) from bus_details", "bus_no");
    }

    
    public void ValidateTrip_Info() {
        if (txtTrip_id.getText().equals("") || txtTStart_time.getText().equals("") || txtTStart_time.getText().equals("") || txtTStop_time.getText().equals("") || txtTrip_Amt.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
            return;
        }
    }
    
    public void clearText() {
        txtTrip_id.setText("");
        txtTStart_time.setText("");
        txtTStop_time.setText("");
        txtTrip_Amt.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTrip_Amt = new javax.swing.JTextField();
        txtTrip_id = new javax.swing.JTextField();
        txtTStart_time = new javax.swing.JTextField();
        txtTStop_time = new javax.swing.JTextField();
        cmbTBus_no = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        cmbTRoute_no = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Trip Information");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, 80));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel3.setText("ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel4.setText("Route No");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel5.setText("Bus No");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel6.setText("Star Time");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel7.setText("Stop Time");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel8.setText("Trip Amount");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, -1));

        txtTrip_Amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrip_AmtActionPerformed(evt);
            }
        });
        jPanel3.add(txtTrip_Amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 140, 30));

        txtTrip_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrip_idActionPerformed(evt);
            }
        });
        jPanel3.add(txtTrip_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 30));

        txtTStart_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTStart_timeActionPerformed(evt);
            }
        });
        jPanel3.add(txtTStart_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 140, 30));

        txtTStop_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTStop_timeActionPerformed(evt);
            }
        });
        jPanel3.add(txtTStop_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 140, 30));

        cmbTBus_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTBus_noActionPerformed(evt);
            }
        });
        jPanel3.add(cmbTBus_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 30));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, -1));

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 90, -1));

        jPanel3.add(cmbTRoute_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 140, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 330, 400));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Route NO", "Bus NO", "Start Time", "Stop Time", "Trip Amt"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 600, 380));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 620, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTrip_AmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrip_AmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrip_AmtActionPerformed

    private void txtTrip_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrip_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrip_idActionPerformed

    private void txtTStart_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTStart_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTStart_timeActionPerformed

    private void txtTStop_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTStop_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTStop_timeActionPerformed

    private void cmbTBus_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTBus_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTBus_noActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ValidateTrip_Info();
        AutoIncrement();
        
        db.InsertData("insert into trip_info(id,route_no,bus_no,start_time,stop_time,amount) values ('" + txtTrip_id.getText() + "','" + cmbTRoute_no.getSelectedItem().toString()+ "','"+cmbTBus_no.getSelectedItem().toString()+"','" + txtTStart_time.getText() + "','" + txtTStop_time.getText() + "','" + txtTrip_Amt.getText() + "')");
        db.getTable(jTable1, "select * from trip_info");
        
        clearText();
        AutoIncrement();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        db.updateRecord("update trip_info set start_time='" + txtTStart_time.getText() + "',stop_time='" + txtTStop_time.getText() + "',amount='"+txtTrip_Amt.getText()+"' where id='" + txtTrip_id.getText() + "'");
        db.getTable(jTable1, "select * from trip_info");
        clearText();
        AutoIncrement();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        db.DeleteData("DELETE FROM `trip_info` WHERE id='" + txtTrip_id.getText() + "'");
        db.getTable(jTable1, "select * from trip_info");
        clearText();
        AutoIncrement();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    
    
    public void AutoIncrement() {
        try {
            String s = "select MAX(id) from trip_info";
            db.DataFound(s);
            int i = 0;
            while (db.rs.next()) {
                i = db.rs.getInt(1);
            }
            txtTrip_id.setText(String.valueOf(i + 1));
        } catch (Exception e) {
            System.out.println(e);
        }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trip_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trip_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trip_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trip_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trip_Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbTBus_no;
    private javax.swing.JComboBox<String> cmbTRoute_no;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTStart_time;
    private javax.swing.JTextField txtTStop_time;
    private javax.swing.JTextField txtTrip_Amt;
    private javax.swing.JTextField txtTrip_id;
    // End of variables declaration//GEN-END:variables
}
